In [3]:
import numpy as np

In [4]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2) #show only second value 

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [16]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(2)

array([0.2977222 , 0.26950097])

In [19]:
np.random.rand(5,5)

array([[0.97958553, 0.82942984, 0.97750946, 0.67544297, 0.66010369],
       [0.47905989, 0.08833557, 0.50705023, 0.24727753, 0.53820887],
       [0.28265417, 0.33813591, 0.55404055, 0.06325712, 0.99686294],
       [0.91786393, 0.56027268, 0.60644038, 0.90528826, 0.8428002 ],
       [0.29901227, 0.53510848, 0.88282578, 0.07980564, 0.23580856]])

In [20]:
np.random.randn(2)

array([1.55110566, 0.25743038])

In [21]:
np.random.randn(5,5)

array([[ 0.77156977, -1.06837836,  3.52743898,  0.07265597, -0.86580584],
       [-0.9195643 , -2.01333115, -0.559016  , -0.8135462 ,  0.09279151],
       [ 0.06991915,  0.11229611, -0.17720187,  0.70367794,  0.47463903],
       [ 1.46502884,  0.20247518, -1.15839593,  1.24367482,  0.47659745],
       [ 1.22633976, -1.21828349, -0.16550075,  0.05499077, -0.66389924]])

In [22]:
np.random.randint(1,100)

95

In [23]:
np.random.randint(1,100,10)

array([22, 88, 89, 26, 16,  5, 31, 66, 97, 87])

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [31]:
ranarr.max()

39

In [32]:
ranarr.argmax()

7

In [33]:
ranarr.min()

2

In [34]:
ranarr.argmin()

9

In [35]:
# Vector
arr.shape

(25,)

In [36]:

arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
arr.reshape(1,25).shape

(1, 25)

In [38]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
arr.reshape(25,1).shape

(25, 1)

In [40]:
arr.dtype

dtype('int64')

In [41]:
arr2 = np.array([1.2, 3.4, 5.6])
arr2.dtype

dtype('float64')