In [1]:
import numpy as np

In [2]:
#Create sample array
arr = np.arange(0,11)

In [3]:
#Show the array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Get a value at an index
arr[8]

8

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
#Create New Array
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:

slice_of_arr = arr[0:6]

#Show slice of array
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
#Change Slice (broadcast new values)
slice_of_arr[:]=99

#Show the slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

This changes the values in the orignal array too

In [11]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
#This is how to make a copy of an array
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [15]:

# Getting individual element value
arr_2d[1][0]


20

In [16]:
#does the same thing as above just a different format
arr_2d[1,0]

20

In [17]:
# 2D array slicing
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [18]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [19]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [20]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [22]:
bool_arr = arr>4

In [23]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [24]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [25]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])